openapi: 3.0.3
info:
  title: Ticket Allocation
  version: 1.0.0
  contact: {}
servers:
  - url: localhost
paths:
  /ticket_options/{ticketOptionID}:
    get:
      summary: Get ticket option
      description: Get Ticket Option by provided Ticket Option ID
      operationId: getTicketOption
      responses:
        '200':
          description: ''
    parameters:
      - name: ticketOptionID
        in: path
        required: true
        schema:
          type: string
  /ticket_options:
    post:
      summary: Create ticket option
      description: Create Ticket Option with given attributes
      operationId: createTicketOption
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    attributes:
                      type: object
                      properties:
                        allocation:
                          type: number
                          example: 100
                        description:
                          type: string
                          example: ticket option description
                        name:
                          type: string
                          example: Test ticket option
                    type:
                      type: string
                      example: ticket_options
            examples:
              Create ticket option:
                value:
                  data:
                    attributes:
                      allocation: 100
                      description: ticket opion description
                      name: Test ticket option
                    type: ticket_options
      responses:
        '200':
          description: ''
  /purchases:
    post:
      summary: Create Purchase
      description: >-
        Create Purchase with quantity and associated User / Ticket Option
        relationship
      operationId: createPurchase
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    attributes:
                      type: object
                      properties:
                        quantity:
                          type: number
                          example: 1
                    relationships:
                      type: object
                      properties:
                        ticket_option:
                          type: object
                          properties:
                            data:
                              type: object
                              properties:
                                id:
                                  type: string
                                  example: '{{ticketOptionID}}'
                                type:
                                  type: string
                                  example: ticket_options
                        user:
                          type: object
                          properties:
                            data:
                              type: object
                              properties:
                                id:
                                  type: string
                                  example: d6abe829-c28c-44ec-bee6-3183f2c53fef
                                type:
                                  type: string
                                  example: users
                    type:
                      type: string
                      example: purchases
            examples:
              Create Purchase:
                value:
                  data:
                    attributes:
                      quantity: 1
                    relationships:
                      ticket_option:
                        data:
                          id: '{{ticketOptionID}}'
                          type: ticket_options
                      user:
                        data:
                          id: d6abe829-c28c-44ec-bee6-3183f2c53fef
                          type: users
                    type: purchases
      responses:
        '200':
          description: ''
tags: []
