// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
)

// CreatePurchaseApplicationVndAPIPlusJSONBody defines parameters for CreatePurchase.
type CreatePurchaseApplicationVndAPIPlusJSONBody struct {
	Data *struct {
		Attributes *struct {
			Quantity *int `json:"quantity,omitempty"`
		} `json:"attributes,omitempty"`
		Relationships *struct {
			TicketOption *struct {
				Data *struct {
					Id   *string `json:"id,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"data,omitempty"`
			} `json:"ticket_option,omitempty"`
			User *struct {
				Data *struct {
					Id   *string `json:"id,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"data,omitempty"`
			} `json:"user,omitempty"`
		} `json:"relationships,omitempty"`
		Type *string `json:"type,omitempty"`
	} `json:"data,omitempty"`
}

// CreateTicketOptionApplicationVndAPIPlusJSONBody defines parameters for CreateTicketOption.
type CreateTicketOptionApplicationVndAPIPlusJSONBody struct {
	Data *struct {
		Attributes *struct {
			Allocation  *int    `json:"allocation,omitempty"`
			Description *string `json:"description,omitempty"`
			Name        *string `json:"name,omitempty"`
		} `json:"attributes,omitempty"`
		Type *string `json:"type,omitempty"`
	} `json:"data,omitempty"`
}

// CreatePurchaseApplicationVndAPIPlusJSONRequestBody defines body for CreatePurchase for application/vnd.api+json ContentType.
type CreatePurchaseApplicationVndAPIPlusJSONRequestBody CreatePurchaseApplicationVndAPIPlusJSONBody

// CreateTicketOptionApplicationVndAPIPlusJSONRequestBody defines body for CreateTicketOption for application/vnd.api+json ContentType.
type CreateTicketOptionApplicationVndAPIPlusJSONRequestBody CreateTicketOptionApplicationVndAPIPlusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create Purchase
	// (POST /purchases)
	CreatePurchase(w http.ResponseWriter, r *http.Request)
	// Create ticket option
	// (POST /ticket_options)
	CreateTicketOption(w http.ResponseWriter, r *http.Request)
	// Get ticket option
	// (GET /ticket_options/{ticketOptionID})
	GetTicketOption(w http.ResponseWriter, r *http.Request, ticketOptionID string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreatePurchase operation middleware
func (siw *ServerInterfaceWrapper) CreatePurchase(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePurchase(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTicketOption operation middleware
func (siw *ServerInterfaceWrapper) CreateTicketOption(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTicketOption(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicketOption operation middleware
func (siw *ServerInterfaceWrapper) GetTicketOption(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "ticketOptionID" -------------
	var ticketOptionID string

	err = runtime.BindStyledParameterWithOptions("simple", "ticketOptionID", mux.Vars(r)["ticketOptionID"], &ticketOptionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketOptionID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicketOption(w, r, ticketOptionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/purchases", wrapper.CreatePurchase).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/ticket_options", wrapper.CreateTicketOption).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/ticket_options/{ticketOptionID}", wrapper.GetTicketOption).Methods(http.MethodGet)

	return r
}

type CreatePurchaseRequestObject struct {
	Body *CreatePurchaseApplicationVndAPIPlusJSONRequestBody
}

type CreatePurchaseResponseObject interface {
	VisitCreatePurchaseResponse(w http.ResponseWriter) error
}

type CreatePurchase201Response struct {
}

func (response CreatePurchase201Response) VisitCreatePurchaseResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type CreatePurchase400Response struct {
}

func (response CreatePurchase400Response) VisitCreatePurchaseResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreatePurchase404Response struct {
}

func (response CreatePurchase404Response) VisitCreatePurchaseResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateTicketOptionRequestObject struct {
	Body *CreateTicketOptionApplicationVndAPIPlusJSONRequestBody
}

type CreateTicketOptionResponseObject interface {
	VisitCreateTicketOptionResponse(w http.ResponseWriter) error
}

type CreateTicketOption201Response struct {
}

func (response CreateTicketOption201Response) VisitCreateTicketOptionResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type CreateTicketOption400Response struct {
}

func (response CreateTicketOption400Response) VisitCreateTicketOptionResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type GetTicketOptionRequestObject struct {
	TicketOptionID string `json:"ticketOptionID"`
}

type GetTicketOptionResponseObject interface {
	VisitGetTicketOptionResponse(w http.ResponseWriter) error
}

type GetTicketOption200Response struct {
}

func (response GetTicketOption200Response) VisitGetTicketOptionResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetTicketOption404Response struct {
}

func (response GetTicketOption404Response) VisitGetTicketOptionResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create Purchase
	// (POST /purchases)
	CreatePurchase(ctx context.Context, request CreatePurchaseRequestObject) (CreatePurchaseResponseObject, error)
	// Create ticket option
	// (POST /ticket_options)
	CreateTicketOption(ctx context.Context, request CreateTicketOptionRequestObject) (CreateTicketOptionResponseObject, error)
	// Get ticket option
	// (GET /ticket_options/{ticketOptionID})
	GetTicketOption(ctx context.Context, request GetTicketOptionRequestObject) (GetTicketOptionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreatePurchase operation middleware
func (sh *strictHandler) CreatePurchase(w http.ResponseWriter, r *http.Request) {
	var request CreatePurchaseRequestObject

	var body CreatePurchaseApplicationVndAPIPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePurchase(ctx, request.(CreatePurchaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePurchase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePurchaseResponseObject); ok {
		if err := validResponse.VisitCreatePurchaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTicketOption operation middleware
func (sh *strictHandler) CreateTicketOption(w http.ResponseWriter, r *http.Request) {
	var request CreateTicketOptionRequestObject

	var body CreateTicketOptionApplicationVndAPIPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTicketOption(ctx, request.(CreateTicketOptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTicketOption")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTicketOptionResponseObject); ok {
		if err := validResponse.VisitCreateTicketOptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTicketOption operation middleware
func (sh *strictHandler) GetTicketOption(w http.ResponseWriter, r *http.Request, ticketOptionID string) {
	var request GetTicketOptionRequestObject

	request.TicketOptionID = ticketOptionID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTicketOption(ctx, request.(GetTicketOptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTicketOption")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTicketOptionResponseObject); ok {
		if err := validResponse.VisitGetTicketOptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
